baseURL = "http://5dfe1cc459b5580008956e4d--trusting-payne-8469ea.netlify.com/"
languageCode = "en-us"
title = "Peter Herring"
theme = "hyde"

[Menus]
  main = [
      {Name = "Facebook", URL = "https://www.facebook.com/petehktrainer1/"},
  ]

[params]
  description = "Just a trainer"
  themeColor = "theme-base-09"
  layoutReverse = true
