baseURL = "https://peterherring.netlify.com/"
languageCode = "en-us"
title = "Peter Herring"
theme = "hyde"
googleAnalytics = "UA-155141808-1"

[Menus]
  main = [
      {Name = "Facebook", URL = "https://www.facebook.com/petehktrainer1/"},
  ]

[params]
  description = "Just a trainer"
  themeColor = "theme-base-09"
  layoutReverse = true
