baseURL = "http://trusting-payne-8469ea.netlify.com/"
languageCode = "en-us"
title = "Peter Herring"
theme = "hyde-hyde"
[params.social]
  facebook = "petehktrainer1"
[params]
  description = "Just a trainer"
  themeColor = "theme-base-08"
  layoutReverse = false
